"""Build a browsable, location-based index of the settlement imagery for GitHub.

    python analysis/hazard_exposure/build_imagery_index.py

Writes outputs/imagery_by_location/:

    imagery_by_location/
    ├── README.md                                   all districts
    └── <District>/
        ├── README.md                               urban and rural local levels of the district
        ├── Urban_municipalities/
        │   ├── README.md
        │   └── <LocalLevel>_<KAR-SET-xxx>/README.md   every image of that settlement, shown inline
        └── Rural_municipalities/ ...

The pages *link to* the original image files in outputs/figures/karnali_79/; no image is moved or
copied, so the dashboard, its database and the Vercel deployment keep working unchanged and the
repository does not grow. The tree is regenerated from the result tables, so re-run this script
after the screening or the epoch-frame export changes (it removes and rebuilds only this folder).
"""
from __future__ import annotations

import csv
import os
import re
import shutil
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "outputs/imagery_by_location"
SCREEN = ROOT / "outputs/tables/karnali_79_exposure_screening.csv"
FRAMES = ROOT / "outputs/tables/karnali_79_epoch_indicators.csv"
FIG = ROOT / "outputs/figures/karnali_79"
EPOCHS = [1972, 1977, 1982, 1987, 1992, 1997, 2002, 2007, 2012, 2017, 2022, 2026]
TYPE_DIR = {"urban municipality": "Urban_municipalities", "rural municipality": "Rural_municipalities"}
HEADER = ("<!-- Generated by analysis/hazard_exposure/build_imagery_index.py; edits will be "
          "overwritten. Images are links to outputs/figures/karnali_79/ (not copies). -->\n")


def safe(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def rel(target: Path, page_dir: Path) -> str:
    return Path(os.path.relpath(target, page_dir)).as_posix()


def num(v, d=0):
    try:
        return f"{float(v):,.{d}f}"
    except (TypeError, ValueError):
        return "–"


def settlement_page(s: dict, frames: list[dict], page_dir: Path) -> str:
    fs = f"{s['settlement_id']}_{slug(s['local_level'])}"
    ts = FIG / "imagery_timeseries" / f"{fs}_timeseries_1972_2026.png"
    sc = FIG / "water_level_scenarios" / f"{fs}_water_level_scenarios.png"
    prof = ROOT / "settlements/settlement_profiles" / f"{fs}.md"
    by_epoch = {int(f["epoch"]): f for f in frames}

    cells = []
    for e in EPOCHS:
        f = by_epoch.get(e)
        if f:
            img = rel(ROOT / f["frame_path"], page_dir)
            cells.append(f'<td align="center"><a href="{img}"><img src="{img}" width="180" alt="{e}"></a><br>'
                         f'<b>{e}</b> · {f["acquired"]}<br><sub>{f["platform"]}, {int(float(f["resolution_m"]))} m</sub></td>')
        else:
            cells.append(f'<td align="center" width="180"><b>{e}</b><br><sub>no usable dry-season image '
                         f'in the archive window</sub></td>')
    grid = "\n".join("<tr>\n" + "\n".join(cells[i:i + 4]) + "\n</tr>" for i in range(0, len(cells), 4))

    ind = "\n".join(
        f"| {f['epoch']} | {f['acquired']} | {f['platform']} | {int(float(f['resolution_m']))} m | "
        f"{num(float(f['valid_fraction']) * 100)}% | "
        + (" | ".join(num(float(f[k]) * 100, 1) + "%" if f[k] else "–" for k in ("veg_fraction", "water_fraction"))
           if f["comparable"] == "True" else "n/c | n/c")
        + f" | [{Path(f['frame_path']).name}]({rel(ROOT / f['frame_path'], page_dir)}) |"
        for f in sorted(frames, key=lambda x: int(x["epoch"])))

    return f"""{HEADER}
# {s['settlement_id']} · {s['settlement_name']}

**{s['local_level']}** {s['local_level_type']} · **{s['district']}** District · Karnali Province
· point {s['lon']}, {s['lat']}

| Buildings in 4×4 km window | HAND ≤ 2 m | HAND ≤ 5 m | HAND ≤ 10 m | Exposure rank | Images |
|---|---|---|---|---|---|
| {num(s['buildings_in_window'])} | {num(s['buildings_le_2m'])} | {num(s['buildings_le_5m'])} | {num(s['buildings_le_10m'])} | {s['exposure_rank_buildings_le_5m']} / 79 | {len(frames)} / 12 epochs |

[Settlement profile]({rel(prof, page_dir)}) ·
[Time-series figure]({rel(ts, page_dir)}) ·
[Low-ground scenario figure]({rel(sc, page_dir)}) ·
[↑ {s['local_level_type'].split()[0].capitalize()} municipalities of {s['district']}](../README.md) ·
[↑ All districts](../../../README.md)

## Satellite images, 1972 → 2026 (one per 5-year epoch)

Click an image to open it at full size. 1972–1982 frames are Landsat MSS false colour (vegetation red).
Frames cover the same 4×4 km window, centred on the settlement point.

<table>
{grid}
</table>

## Time-series figure

![Time series]({rel(ts, page_dir)})

## Low-ground (HAND) scenarios and built-up history

![Scenarios]({rel(sc, page_dir)})

## Image list and indicators

| Epoch | Acquired | Sensor | Res. | Clear | Vegetation | Water | File |
|---|---|---|---|---|---|---|---|
{ind}

n/c = not comparable (uncalibrated 1970s MSS). Exposure screening only, not a risk-to-life estimate;
see [docs/limitations.md]({rel(ROOT / 'docs/limitations.md', page_dir)}).
"""


def main():
    settlements = list(csv.DictReader(open(SCREEN)))
    frames = defaultdict(list)
    for f in csv.DictReader(open(FRAMES)):
        frames[f["settlement_id"]].append(f)
    assert len(settlements) == 79

    if OUT.exists():
        shutil.rmtree(OUT)
    tree = defaultdict(lambda: defaultdict(list))
    for s in sorted(settlements, key=lambda r: (r["district"], r["local_level"])):
        d, t = safe(s["district"]), TYPE_DIR[s["local_level_type"]]
        folder = f"{safe(s['local_level'])}_{s['settlement_id']}"
        page_dir = OUT / d / t / folder
        page_dir.mkdir(parents=True)
        (page_dir / "README.md").write_text(settlement_page(s, frames[s["settlement_id"]], page_dir))
        tree[s["district"]][t].append((folder, s))

    def table(items, prefix=""):
        return "\n".join(
            f"| [{s['local_level']}]({prefix}{folder}/README.md) | {s['settlement_name']} | {s['settlement_id']} | "
            f"{num(s['buildings_in_window'])} | {num(s['buildings_le_5m'])} | {len(frames[s['settlement_id']])}/12 |"
            for folder, s in items)

    cols = "| Local level | Settlement | ID | Buildings | HAND ≤ 5 m | Images |\n|---|---|---|---|---|---|"
    for district, types in tree.items():
        ddir = OUT / safe(district)
        parts = []
        for t in ("Urban_municipalities", "Rural_municipalities"):
            items = types.get(t, [])
            label = t.replace("_", " ")
            (ddir / t).mkdir(exist_ok=True)
            (ddir / t / "README.md").write_text(
                f"{HEADER}\n# {district} District · {label}\n\n[↑ {district} District](../README.md) · "
                f"[↑ All districts](../../README.md)\n\n" + (f"{cols}\n{table(items)}\n" if items else
                f"No {label.lower()} in {district} District.\n"))
            parts.append(f"## [{label}]({t}/README.md) ({len(items)})\n\n" +
                         (f"{cols}\n{table(items, t + '/')}\n" if items else f"None in {district} District.\n"))
        (ddir / "README.md").write_text(f"{HEADER}\n# {district} District\n\n[↑ All districts](../README.md)\n\n"
                                        + "\n".join(parts))

    rows = "\n".join(
        f"| [{d}]({safe(d)}/README.md) | {len(t.get('Urban_municipalities', []))} | "
        f"{len(t.get('Rural_municipalities', []))} | "
        f"{sum(len(frames[s['settlement_id']]) for v in t.values() for _, s in v)} |"
        for d, t in sorted(tree.items()))
    (OUT / "README.md").write_text(f"""{HEADER}
# Settlement imagery by location

Browse the satellite images of the 79 screened settlements by **District → Urban / Rural municipalities →
Local level**. Each local-level folder has a page showing all of its images (1972–2026, one per 5-year epoch),
its time-series figure and its low-ground scenario figure.

The pages link to the original files in [`outputs/figures/karnali_79/`](../figures/karnali_79/). Nothing is
copied or moved, so the dashboard and deployment are unaffected. Regenerate with
`python analysis/hazard_exposure/build_imagery_index.py`.

| District | Urban municipalities | Rural municipalities | Images |
|---|---|---|---|
{rows}
| **Total** | **25** | **54** | **{sum(len(v) for v in frames.values())}** |

Where the files are:

| Folder | Contents |
|---|---|
| `outputs/figures/karnali_79/epoch_frames/KAR-SET-xxx/<epoch>.jpg` | one 400×400 px image per settlement and epoch |
| `outputs/figures/karnali_79/imagery_timeseries/` | 12-epoch time-series figure per settlement |
| `outputs/figures/karnali_79/water_level_scenarios/` | HAND scenario and built-up figure per settlement |
| `outputs/maps/karnali_79_overview_exposure_screening.png` | province overview map |
""")
    n = sum(1 for _ in OUT.rglob("README.md"))
    print(f"wrote {n} index pages under {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
